# Generated by Django 3.1.3 on 2020-12-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201201_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Preco'),
        ),
    ]
