# Generated by Django 3.1.3 on 2020-12-01 19:29

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201201_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(default=6, upload_to=core.models.get_file_path, verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
