# Generated by Django 3.1.3 on 2020-12-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201201_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('resumo', models.CharField(max_length=200, verbose_name='resumo')),
                ('descricao', models.TextField(max_length=2000, verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
