# Generated by Django 3.1.3 on 2020-12-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tickets'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
