version: '3.8'

services:
  banco: 
   image: mysql
   container_name: banco   
   ports:
    - "3307:3306"
   command: --default-authentication-plugin=mysql_native_password
   environment:
    MYSQL_ROOT_PASSWORD: MySQL2020
    MYSQL_DATABASE: django2
    MYSQL_USER: root
    MYSQL_PASSWORD: MySQL2020
   volumes:
    - ./data:/var/lib/mysql
    - ./site/pessoa.sql:/docker-entrypoint-initdb.d/pessoa.sql 
   networks:
    - rede-mysql-compose
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks: 
      - rede-mysql-compose
    depends_on:
      - banco

networks:
  rede-mysql-compose:
    driver: bridge





        
